# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2a79ca0960e6cb444bce18339979471b96b33d8748c64e7cf15c59571cb3f5e5bd3481fd8814220d0158ee4ff4408ba49a9d208fad34b2a427d13f7d81643a9

test:
  secret_key_base: 2f319e84ee1a948c3e37c44e749bde35beef7b4f71b5b9181d6fdc53ba11b335d1fbb0c359280b02d10236202eea725b7dd2db40fd8165415dd947a3895d820e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
